version: "3.8"
services:

  jenkins:
    container_name: jenkins
    build:
      context: ./jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      restart_policy:
        condition: on-failure

  sonarqube:
    container_name: sonarqube
    image: sonarqube:lts-community
    stop_grace_period: 3600s
    ports:
      - 9000:9000
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonarqube-database:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    depends_on: 
    - sonarqube-database
    deploy:
      restart_policy:
        condition: on-failure

  sonarqube-database:
    image: postgres:15.4-alpine3.18
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - sonarqube_postgresql:/var/lib/postgresql
      - sonarqube_postgresql_data:/var/lib/postgresql/data
    
volumes:
  jenkins_home:
    external: true
    name: jenkins_home
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_postgresql:
  sonarqube_postgresql_data: